version: '3.8'
services:
  air:
    image: cosmtrek/air:latest
    depends_on:
      - db
    working_dir: /usr/src/app
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  pgdata:
