version: '3.8'
services:
  # app:
    # build: .
    # ports:
    #   - "8081:8081"
    # depends_on:
    #   - db
    # volumes:
    #   - ./:/app
 
  db:
    image: postgres:latest
    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  pgdata:
